<?php

namespace Src;

use \Mpdf\Mpdf;

/**
 * @author Boudouma Mohamed Ilies <medilies.contact@gmail.com>
 */
class Pdf
{
    //********************************************* */
    //          Static properties
    //********************************************* */
    /**
     * The maximum number of records to render per page
     * 
     * @var int
     */
    public static $max_cards_per_page;

    /**
     * The absolute path of the HTML template
     * 
     * @var string
     */
    public static $template_html_path;

    /**
     * The absolute path of the template's stylesheet. Deduced from $html_template
     * 
     * @var string
     */
    public static $template_css_path;

    /**
     * The absolute path to where CSV files generated by instances of this class would be outputed
     * 
     * @var string
     */
    public static $output_folder;

    //********************************************* */
    //          Instance (This pdf) properties
    //********************************************* */
    protected $csv_file;
    protected $fields;
    protected $number_of_rows;

    protected $pdf_name;

    protected $pdf;

    function __construct(array $csv_file, array $fields, string $pdf_name)
    {
        $this->csv_file = $csv_file;
        $this->fields = $fields;
        $this->pdf_name = $pdf_name;

        $this->number_of_rows = sizeof($this->csv_file);

        $this->pdf = new Mpdf([
            'orientation' => 'P',
            'margin_top' => 30
        ]);

        $this->pdf->autoScriptToLang = true;
        $this->pdf->autoLangToFont = true;
        $this->pdf->SetDirectionality('ltr');
        $this->pdf->setFooter('{PAGENO}');

        $this->render();
        $this->setPdfMeta();
        // Dump file
        $output_name = self::$output_folder . "/" . $this->pdf_name;
        $this->pdf->Output($output_name, 'F');
        echo $output_name . PHP_EOL;
    }

    protected function render()
    {
        $template = file_get_contents(Self::$template_html_path);

        // Write the stylesheet
        $pdf_style = file_get_contents(Self::$template_css_path);
        $this->pdf->WriteHTML($pdf_style, 1); // The parameter 1 tells mPDF that this is CSS and not HTML

        $this->pdf->SetHTMLHeader($this->pdf_name);

        // Preparing for bulk replace
        $all_possible_patterns =  array_map(
            fn (string $key): string => "%VAR_$key%",
            $this->fields
        );

        for ($i = 0; $i < $this->number_of_rows; $i++) {
            $all_row_data = $this->csv_file[$i];

            // Bulk replace: an array of strings(pattenrs) replaced with an array of strings(data)
            $substituted_text = str_replace($all_possible_patterns, $all_row_data, $template);

            // Writting the card
            $this->pdf->WriteHTML($substituted_text, 2);

            $this->checkForAddingNewPage($i);
        }
    }

    protected function checkForAddingNewPage($iteration): void
    {
        // avoid empty pages
        if ($iteration + 1 === $this->number_of_rows) {
            return;
        }
        if (($iteration + 1) % Self::$max_cards_per_page === 0) {
            $this->pdf->AddPage();
        }
    }

    protected function setPdfMeta(): void
    {
        $this->pdf->SetTitle("Cards");
        $this->pdf->SetAuthor(base64_decode('Qm91ZG91bWEgTW9oYW1lZCBJbGllcw=='));
        $this->pdf->SetCreator(base64_decode('aHR0cHM6Ly9naXRodWIuY29tL21lZGlsaWVz'));
        $this->pdf->SetSubject("pdf cards");
        $this->pdf->SetKeywords("pdf,cards");
    }
}
